/* Group */
create or replace NONEDITIONABLE TRIGGER TR_GROUP 
AFTER DELETE OR INSERT OR UPDATE OF ISACTIVE,NAME,PRIORITY ON ZAPP_GROUP 
BEGIN

  DBMS_MVIEW.REFRESH('zapp_group_mv');

  NULL;
END;

/* Group User */
create or replace NONEDITIONABLE TRIGGER TR_GROUPUSER 
AFTER DELETE OR INSERT OR UPDATE OF GROUPUSERID ON ZAPP_GROUPUSER 
BEGIN

  DBMS_MVIEW.REFRESH('zapp_groupuser_mv');

  NULL;
END;